### ISSUE TITLE
2025-05-12 GCP Compute Engine 인스턴스 내 로그 추출 관련 문제

### ISSUE THREAD

**Issue by koojun99** [100-hours-a-week/3-team-ssammu-wiki#77]
# 2025-05-12 GCP Compute Engine 인스턴스 내 로그 추출 관련 문제

## 🐞 에러 내용
- GCP Cloud Monitoring(Log Explorer)에서 Spring Boot 애플리케이션 로그가 보이지 않음.

## 🔍 원인 분석
- GCP Compute Engine 인스턴스에 **Ops Agent(Fluent Bit 기반)**는 기본적으로 설치되어 있었음.

- 하지만 app.log와 같은 사용자 정의 로그 경로를 수집하도록 설정되어 있지 않음.

- 따라서 로그 파일은 존재하지만, Fluent Bit이 수집하지 않아 GCP에 전송되지 않음.

## ✅ 해결 방법
- /etc/google-cloud-ops-agent/config.yaml에 다음 설정을 추가:
``` yaml

logging:
  receivers:
    spring_log:
      type: files
      include_paths:
        - /home/ssmu-morgan/app.log
      record_log_file_path: true

  service:
    pipelines:
      default_pipeline:
        receivers: [spring_log]
```
- 설정 반영:

``` bash
sudo systemctl restart google-cloud-ops-agent
```
- Log Explorer에서 "spring_log" 관련 로그 확인

## 회고
- GCP 인스턴스 생성 시 Ops Agent가 설치되어 있어도, 사용자 정의 로그는 명시적으로 설정해줘야 한다는 점을 명확히 인지함.

- 추후 로그 수집을 위해 GCP Ops Agent 설정 구조(receivers, pipelines)에 대한 이해가 필수적임.
